### Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json
Accept-Language:EN

{
  "name": "Eshmat",
  "surname": "Eshmatov",
  "email": "codeuz91@gmail.com",
  "password": "1234"
}


### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "hojiakbar@gmail.com",
  "password": "1234"
}


### Verification
GET http://localhost:8080/auth/verification/18
Accept-Language: EN


###  registration resend
GET http://localhost:8080/auth/registration/resend/codeuz91@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwMTkwNDgsImlkIjoyLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJob2ppYWtiYXJAZ21haWwuY29tIiwiZXhwIjoxNzIwMzY0NjQ4LCJpc3MiOiJZb3V0dWJlIn0.uHdPxJFFyRtzuTo71LKUG7zq0BCidAIP8jBueE6CVySdPcTov5i7gkXJEnDzKhLTxiujjpWBfoSZ_w6I0cLmdA
