### create profile
POST http://localhost:8080/profile/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk2NDMwNDEsImlkIjoxLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJuYW1lIjoiaG9qaWFrYmFyYW5kYXVsb3Y1QGdtYWlsLmNvbSIsImV4cCI6MTcxOTk4ODY0MSwiaXNzIjoiWW91dHViZSJ9.zG1HufJvesDIhZ41_NqoPvuTEohwxkJ0n9AchzZV68hmYFPIW-EJpNn7TUirYElYCaqb5DsdQvzeQErZENDlWg

{
  "name": "Ali",
  "surname": "Alijon",
  "email": "alish@gmail.com",
  "role" : "ROLE_USER"
}

### change password
POST http://localhost:8080/profile/change/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTk2Njg3NzYsImlkIjoxMiwicm9sZSI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiYWtvYmlycW9kaXJpeUBnbWFpbC5jb20iLCJleHAiOjE3MjAwMTQzNzYsImlzcyI6IllvdXR1YmUifQ._-jbH4IZfy3GjQqe7nlJtuo0OT1UEf7-fJbIAueRQUAsMjJaJJsHNhU0c-s8qS5o1T7fliQxsMRO4g4MUVcF4g

{
  "oldPassword": "12345",
  "newPassword": "54321"
}