###
POST http://localhost:8080/video/create/video
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAwODQ0NTQsImlkIjoyLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJob2ppYWtiYXJAZ21haWwuY29tIiwiZXhwIjoxNzIwNDMwMDU0LCJpc3MiOiJZb3V0dWJlIn0.mH3IooJE37weJJCnDG8qY4VMGRKEC6iK3_KJzxNglU7ZiJBNcabUjWO6nd9xs6MD9_xv8bdZbFkys2ufM7gxvg

{
  "title": "Lesson_1",
  "description": "dasturlashni sifatli materiallar orqali o'rganing",
  "channelId": "37f3ea0d-ef66-4620-9dc4-bd65681c138d",
  "type": "VIDEO",
  "status": "PRIVATE",
  "attachId": "f4a8a1db-4c8d-4888-80fc-aad82e0e06f1.jpg",
  "categoryId": 1
}

###
PUT http://localhost:8080/video/update/video/108b7a96-ac58-4b68-bf6f-141db1049336
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA0NDcxMjMsImlkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJoYW5kYXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzIwNzkyNzIzLCJpc3MiOiJZb3V0dWJlIn0.uDoCLBUfqR34GRSfcjnHVJMJ-BaSmHH4lqAeKiIUgFtpJ4VU6HyULQbz65ndPdgFdm4OIaJRCx13K7FrOvqItg

{
  "title": "Lesson_1.2",
  "description": "dasturlashni sifatli videolardan o'rganing",
  "type": "VIDEO",
  "status": "PRIVATE",
  "attachId": "f4a8a1db-4c8d-4888-80fc-aad82e0e06f1.jpg",
  "categoryId": 1
}

### change status
PUT http://localhost:8080/api/v1/video/status/108b7a96-ac58-4b68-bf6f-141db1049336
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA0NDcxMjMsImlkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJoYW5kYXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzIwNzkyNzIzLCJpc3MiOiJZb3V0dWJlIn0.uDoCLBUfqR34GRSfcjnHVJMJ-BaSmHH4lqAeKiIUgFtpJ4VU6HyULQbz65ndPdgFdm4OIaJRCx13K7FrOvqItg

### view_count
PUT http://localhost:8080/api/v1/video/view_count/108b7a96-ac58-4b68-bf6f-141db1049336
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3MjM1NDAsImlkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJoYW5kYXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzIxMDY5MTQwLCJpc3MiOiJZb3V0dWJlIn0.CZ-caXC6IECw5w6rRVHRrWfghEAe7ylm4KfljbWThIVahcd42JTWrMUzAQt2DSAtf9z5qtvG3kjNUgY_ppERZA

### pagination
GET http://localhost:8080/api/v1/video/pagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3MjM1NDAsImlkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJoYW5kYXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzIxMDY5MTQwLCJpc3MiOiJZb3V0dWJlIn0.CZ-caXC6IECw5w6rRVHRrWfghEAe7ylm4KfljbWThIVahcd42JTWrMUzAQt2DSAtf9z5qtvG3kjNUgY_ppERZA

### By Title
GET http://localhost:8080/api/v1/video/by/Lesson_1.2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3MjM1NDAsImlkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJoYW5kYXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzIxMDY5MTQwLCJpc3MiOiJZb3V0dWJlIn0.CZ-caXC6IECw5w6rRVHRrWfghEAe7ylm4KfljbWThIVahcd42JTWrMUzAQt2DSAtf9z5qtvG3kjNUgY_ppERZA

### by Tag Id
GET http://localhost:8080/api/v1/video/tag/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3MjM1NDAsImlkIjozLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJoYW5kYXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzIxMDY5MTQwLCJpc3MiOiJZb3V0dWJlIn0.CZ-caXC6IECw5w6rRVHRrWfghEAe7ylm4KfljbWThIVahcd42JTWrMUzAQt2DSAtf9z5qtvG3kjNUgY_ppERZA


